# Generated by Django 5.1.5 on 2026-06-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='application_recipie_14aafe_idx',
            old_name='applicatio_recipient_58b5de_idx',
        ),
    ]
